---
name: OpenSSL Docker Image

'on':
  push:
    paths:
      - Dockerfile
      - VERSION

  pull_request:
    paths:
      - Dockerfile
      - VERSION

jobs:
  build:
    if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Grab the version to use.
        id: vars
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Get timestamp for CI tag
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Build the Docker image.
        uses: docker/build-push-action@v6
        with:
          build-args: |
            VERSION=${{ steps.vars.outputs.version }}
          tags: dcjulian29/openssl:${{ steps.vars.outputs.version }}-${{ steps.format-time.outputs.replaced }}

  release:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    name: Release Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Login to DockerHub.
        uses: docker/login-action@v3
        with:
          username: dcjulian29
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Grab the version to use.
        id: vars
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image.
        uses: docker/build-push-action@v6
        with:
          build-args: |
            VERSION=${{ steps.vars.outputs.version }}
          push: true
          tags: dcjulian29/openssl:${{ steps.vars.outputs.version }},dcjulian29/openssl:latest
